//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoutePlanner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RoutePlanner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vinnytsia,Вінниця
        ///Dnieper,Дніпро
        ///Donetsk,Донецьк
        ///Zhytomyr,Житомир
        ///Zaporizhzhia,Запоріжжя
        ///IvanoFrankivsk,Івано-франківськ
        ///Kiev,Київ
        ///Kovel,Ковель
        ///Korosten,Коростень
        ///Kremenchug,Кременчук
        ///Kropivnitsky,Кропивницький
        ///Lugansk,Луганськ
        ///Lutsk,Луцьк
        ///Lviv,Львів
        ///Melitopol,Мелітополь
        ///Mykolayiv,Миколаїв
        ///Mukachevo,Мукачево
        ///Nemiroff,Немирів
        ///Odessa,Одеса
        ///Pervomaysk,Первомайськ
        ///Poltava,Полтава
        ///Rivne,Рівне
        ///Sarny,Сарни
        ///Simferopol,Сімферополь
        ///Sumy,Суми
        ///Ternopil,Тернопіль
        ///Uzhhorod,Ужгород
        ///Uman,Умань
        ///K [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DotBlack {
            get {
                object obj = ResourceManager.GetObject("DotBlack", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap DotRed {
            get {
                object obj = ResourceManager.GetObject("DotRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Помилка вводу! Кількість обраних міст повинна бути не меньше двух..
        /// </summary>
        public static string ErrorCitiesAmount {
            get {
                return ResourceManager.GetString("ErrorCitiesAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Map {
            get {
                object obj = ResourceManager.GetObject("Map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Route {
            get {
                object obj = ResourceManager.GetObject("Route", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon RouteIco {
            get {
                object obj = ResourceManager.GetObject("RouteIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 0 0 127 0 0 0 0 0 0 0 0 0 0 0 0 0 47 0 0 0 0 0 0 0 0 0 0 0 0 121 0 0 0
        ///0 0 268 0 85 0 0 0 0 161 246 0 0 0 0 321 0 0 0 0 0 0 0 0 0 0 0 0 218 0 0 286 0 0
        ///0 268 0 0 280 0 0 0 0 0 0 165 0 0 300 0 0 0 0 0 0 0 0 0 0 0 0 0 303 0 0 0 0 0
        ///127 0 0 0 0 0 140 0 87 0 0 0 0 0 0 0 0 0 0 0 0 188 0 0 0 0 0 0 0 0 184 0 0 0
        ///0 85 280 0 0 0 0 0 0 0 0 0 0 0 127 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0 0 132 0 0 280 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 135 0
        ///0 0 0 140 0 0 0 0 159 0 0 0 0 0 0 0 0 0 0 0 344 0  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Routes {
            get {
                return ResourceManager.GetString("Routes", resourceCulture);
            }
        }
    }
}
